version: '3.8'

services:
  web:
    container_name: ${CONTAINER_SITE_NAME}
    restart: unless-stopped
    build: .
    command: bin/rails server -b 0.0.0.0
    volumes:
      - ./storage:/rails/storage
    ports:
      - "${EXPOSE_PORT}:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
    default:
      external:
        name: ${NETWORK}